Algoritmo "Contagemregressiva"
// Disciplina  : [Lógica de Programação]
// Professor   : Jaja Costa
// Descrição   : Contagem regressiva de 10 a 0! (função)
// Autor(a)    : Caroline Mota
// Data atual  : 25/09/2025
Var
   // Seção de Declarações das variáveis
   i: inteiro
Inicio
   // Seção de Comandos, procedimento, funções, operadores, etc...
   Para i de 10 ate 1 passo -1 faca
      Escreva(i)
   FimPara
   Escreva("FIM!")
Fimalgoritmo